const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const context=vm.createContext({ArkUI:{}});
for(const file of ['js/ark/vendor/engines.js','js/ark/scene-state.js','js/ark/mesh-drag.js']) vm.runInContext(fs.readFileSync(file,'utf8'),context);
const events={}, captures=new Set();
const element={tabIndex:-1,setAttribute(){},classList:{add(){},remove(){}},focus(){},getBoundingClientRect:()=>({width:360}),addEventListener:(type,fn)=>events[type]=fn,setPointerCapture:id=>captures.add(id),hasPointerCapture:id=>captures.has(id),releasePointerCapture:id=>captures.delete(id)};
const state=context.ArkUI.sceneState;context.ArkUI.bindMeshDrag(element,state);
const event=(extra={})=>Object.assign({pointerId:1,button:0,isPrimary:true,clientX:100,clientY:100,preventDefault(){}},extra);
state.pause(true);events.pointerdown(event());events.pointermove(event({clientX:220,clientY:40}));
assert.equal(state.get().rotation[0],30);assert.equal(state.get().rotation[1],60);assert(captures.has(1));
events.pointermove(event({pointerId:2,clientX:700}));assert.equal(state.get().rotation[1],60);
events.pointercancel(event());assert(!captures.has(1));
events.pointermove(event({clientX:700}));assert.equal(state.get().rotation[1],60);
events.keydown({key:'Home',preventDefault(){}});assert.equal(state.get().rotation[1],0);
events.pointerdown(event({pointerType:'touch'}));events.pointermove(event({clientX:1000,clientY:1000}));
assert.equal(state.get().rotation[0],-90);assert.equal(state.get().rotation[1],90);
state.navigate('proximity');assert.equal(captures.size,0);
events.keydown({key:'ArrowRight',shiftKey:true,preventDefault(){}});assert.equal(state.get().rotation[1],105);
events.pointerdown(event({button:2}));assert.equal(captures.size,0);
console.log('PASS: two-axis mouse/touch drag, capture, cancellation, secondary pointer rejection, angle wrapping, paused interaction, navigation cleanup, keyboard reset.');
