/* Shared particle shader sources; no DOM or renderer lifecycle. */
var ParticleShaders = (function () {
  var vertexSource = [
    'precision highp float;',
    'attribute vec3 aPosition;',
    'attribute vec4 aIceberg;',
    'uniform vec3 uIcebergPlacement;',
    'attribute vec3 aProximity;',
    'attribute vec3 aWord;',
    'attribute vec3 aWordFrom;',
    'attribute float aSeed;',
    'attribute float aRecess;',
    'uniform float uTime;',
    'uniform float uSurfaceTime;',
    'uniform float uLightTheme;',
    'uniform vec3 uLayerPose;',
    'uniform float uHome;',
    'uniform float uPixelRatio;',
    'uniform float uState;',
    'uniform float uDissolve;',
    'uniform float uBurst;',
    'uniform float uTrail;',
    'uniform vec4 uShape;',
    'uniform vec4 uSurface;',
    'uniform vec4 uPageSurface;',
    'uniform vec4 uReferenceA;',
    'uniform vec2 uReferenceB;',
    'uniform float uWordBlend;',
    'uniform vec2 uRotation;',
    'uniform vec2 uPointer;',
    'uniform vec2 uProjection;',
    'uniform vec2 uFieldExtent;',
    'varying mediump float vAlpha;',
    'varying mediump vec3 vColor;',
    'varying mediump float vSeed;',
    'void main(){',
    '  vec3 p=aPosition;',
    '  /* Home mesh: quantized coordinates turn the zero state into a field of blocks. */',
    '  vec3 zeroBlock=vec3(floor((p.x+.84)*7.0)/7.0-.42,floor((p.y+.84)*7.0)/7.0-.42,floor((p.z+.60)*4.0)/4.0-.60);',
    '  p=mix(p,zeroBlock,.58);',
    '  float az=aSeed*6.283185;',
    '  float sphereY=aPosition.y;',
    '  float sphereR=sqrt(max(0.0,1.0-sphereY*sphereY));',
    '  float facet=1.0+.075*cos(az*4.0)+.025*cos(az*8.0);',
    '  vec3 orbRaw=vec3(cos(az)*sphereR,sphereY,sin(az)*sphereR)*.96*facet;',
    '  float cubeFace=max(max(abs(orbRaw.x),abs(orbRaw.y)),abs(orbRaw.z));',
    '  vec3 orb=orbRaw/max(cubeFace,.001)*.88;',
    '  vec3 blockStep=floor((orb+.88)*5.0)/5.0-.88;',
    '  orb=mix(orb,blockStep,.34);',
    '  float theta=atan(aPosition.y,aPosition.x);',
    '  float tube=length(aPosition.xy)-.735;',
    '  float knotR=.64+.11*cos(theta*4.0)+tube*.42;',
    '  float stepTheta=(floor((theta+3.141593)*8.0)/8.0-3.5/8.0);',
    '  float tier=floor((aPosition.z+.72)*5.0)/5.0-.36;',
    '  vec3 knot=vec3(cos(stepTheta*2.0)*knotR,sin(stepTheta*2.0)*knotR,tier*.62+.06*cos(stepTheta*8.0));',
    // Every state grows from the same circular rim. Matching angular coordinates
    // keep the surface attached during morphs instead of crossing through the zero.
    '  float recessed=step(.00001,aRecess);',
    '  float crest=0.0, sheetLight=1.0, reach=0.0;',
    '  if(recessed>.5){',
    '    float strandCoord=min(aRecess,.999999)*96.0;',
    '    reach=(floor(strandCoord)+.5)/96.0;',
    '    float angle=fract(strandCoord)*6.283185;',
    '    float envelope=smoothstep(0.0,.4,reach);',
    '    float extent=max(uFieldExtent.x,uFieldExtent.y)*1.48;',
    '    float growth=pow(reach,2.2)*(extent-.96);',
    // Three states extend from the rim; the middle spiral contracts into the opening.
    // They retain the same centre and particle correspondence during travel.
    '    float echo=.96+growth;',
    '    float spiral=.10+.26*pow(reach,.75)*(.86+.14*cos(angle*3.0-reach*5.0));',
    '    float unfurl=.96+growth*(1.0+.50*cos(angle*4.0-reach*1.5)*envelope);',
    '    float radius=dot(vec4(echo,0.0,spiral,unfurl),uSurface);',
    '    float z=-.32-reach*.85+envelope*uSurface.w*cos(angle*2.0)*.22;',
    '    z=mix(z,-.30-reach*.32,uSurface.z);',
    '    p=vec3(cos(angle)*radius,sin(angle)*radius,z);',
    '    crest=.5+.5*cos(angle-reach*2.0);',
    '    sheetLight=.65+.35*crest;',
    '  }',
    // Route depth and idle morphing share the persistent surface, with one clock
    // for page entry/exit. The cycle continues from its current form.
    '  if(recessed>.5){',
    // Page references are still, compact symbols: filaments, grid, stacked leaves,
    // depth contours, linked loops and a framing arc. Weights support reversals.
    '    float a=fract(min(aRecess,.999999)*96.0)*6.283185;',
    '    float band=floor(reach*3.0);',
    '    float ribbon=fract(reach*3.0);',
    '    vec3 ref=vec3(0.0);',
    '    ref+=vec3(cos(a)*(1.0+ribbon*.2),sin(a)*(.40+ribbon*.1)+(band-1.0)*.40,(band-1.0)*.16)*uReferenceA.x;',
    '    ref+=vec3((a/3.141593-1.0)*1.2,(reach*2.0-1.0)*1.2,sin(a)*.12)*uReferenceA.y;',
    '    ref+=vec3(cos(a)*(1.0+ribbon*.12)+(band-1.0)*.14,sin(a)*.55+(band-1.0)*.35,-band*.15)*uReferenceA.z;',
    '    ref+=vec3(cos(a)*(.5+reach*.7),sin(a)*(.5+reach*.7),-reach*.7)*uReferenceA.w;',
    '    ref+=vec3(cos(a)*(.55+ribbon*.10)+(band-1.0)*.50,sin(a)*(.55+ribbon*.10),-band*.12)*uReferenceB.x;',
    '    ref+=vec3(cos(a*.65-.5)*(1.0+reach*.22),sin(a*.65-.5)*1.25,-reach*.2)*uReferenceB.y;',
    '    p=p*uHome+ref;',
    '    p.xy*=uPageSurface.y;',
    '    float routeCos=cos(uPageSurface.z),routeSin=sin(uPageSurface.z);',
    '    p=vec3(p.x,p.y*routeCos-p.z*routeSin,p.y*routeSin+p.z*routeCos);',
    '    p.x+=uPageSurface.w;',
    '    p.z+=uPageSurface.x;',
    '  }',
    '  p=mix(p,orb,uShape.x*(1.0-recessed));',
    '  p=mix(p,knot,uShape.y*(1.0-recessed));',
    '  p=mix(p,aProximity,uShape.z*(1.0-recessed));',
    '  p=mix(p,mix(aWordFrom,aWord,uWordBlend),uShape.w*(1.0-recessed));',
    '  vSeed=aSeed;',
    '  p.z+=sin(aSeed*25.0+uTime*.24)*.018*(1.0-recessed);',
    '  float scatter=smoothstep(aSeed*.78,aSeed*.78+.22,uDissolve)*(1.0-recessed);',
    '  float angle=aSeed*71.7;',
    '  vec3 drift=vec3(cos(angle),sin(angle*1.37),sin(angle*.73));',
    '  p+=scatter*(drift*mix(.58,.065,uShape.z)+p/max(length(p),.001)*mix(.12,.025,uShape.z));',
    '  p.xy+=scatter*mix(.08,.012,uShape.z)*vec2(sin(uTime*.21+angle),cos(uTime*.17+angle));',
    '  p.z+=uBurst*scatter*sin(angle*.73)*1.8-uTrail*.32;',
    '  float ay=uRotation.y+(1.0-uShape.w)*(1.0-recessed)*uPointer.x*.11;',
    '  float ax=uRotation.x-(1.0-uShape.w)*(1.0-recessed)*uPointer.y*.075;',
    '  ay*=mix(1.0,uHome,recessed); ax*=mix(1.0,uHome,recessed);',
    '  float cy=cos(ay),sy=sin(ay),cx=cos(ax),sx=sin(ax);',
    '  p=vec3(p.x*cy+p.z*sy,p.y,-p.x*sy+p.z*cy);',
    '  p=vec3(p.x,p.y*cx-p.z*sx,p.y*sx+p.z*cx);',
    '  float stateTilt=uState*.22*(1.0-recessed);',
    '  float cz=cos(stateTilt),sz=sin(stateTilt);',
    '  p=vec3(p.x*cz-p.y*sz,p.x*sz+p.y*cz,p.z);',
    '  float depth=1.0+uState*.10*(1.0-recessed)-p.z*.06;',
    '  vec2 projected=p.xy*.72*uProjection/depth;',
    '  projected=mix(projected,(projected*1.2-uLayerPose.xy)/max(uLayerPose.z,.01),recessed);',
    // Both persistent meshes meet at one waterline in the Theory composition.
    '  vec2 iceProjected=(aIceberg.xy+vec2(aIceberg.z*.22,aIceberg.z*.14))*.72*uProjection*uIcebergPlacement.z+uIcebergPlacement.xy;',
    // Water is viewport-wide while the iceberg remains fitted to its page anchor.
    '  float water=step(.800001,aRecess);',
    '  iceProjected.x=mix(iceProjected.x,aIceberg.x/1.25*1.04,water);',
    '  iceProjected=(iceProjected-uLayerPose.xy)/max(uLayerPose.z,.01);',
    '  projected=mix(projected,iceProjected,uReferenceA.w);',
    '  gl_Position=vec4(projected,0.0,1.0);',
    '  float focus=abs(p.z-.10);',
    '  float blur=scatter*.12+uShape.z*smoothstep(.07,.48,focus)*.6;',
    '  gl_PointSize=(mix(1.5+aSeed*1.8,1.65+aSeed*.75,uShape.z)+blur*8.0)*uPixelRatio;',
    '  float light=smoothstep(-.95,.72,p.y);',
    '  vAlpha=(.24+light*.82)/(1.0+blur*3.6)*mix(1.0,.16,scatter)*mix(.52,1.4,max(uShape.z,uShape.w));',
    '  vAlpha*=mix(1.0,.22,step(.01,uTrail))*(1.0-recessed*step(.01,uTrail));',
    '  float recessWeight=recessed;',
    '  crest=mix(.5,crest,uHome); sheetLight=mix(.8,sheetLight,uHome);',
    '  vAlpha=mix(vAlpha,(.62+crest*.32)*(1.0-smoothstep(.6,1.0,reach)*.65)*(1.0-step(.01,uTrail)),recessWeight);',
    // Additive particles have no solid occlusion: reserve the foreground zero's
    // projected annulus so the background cannot wash over its silhouette.
    '  vec2 front=p.xy/depth;',
    '  front=vec2(front.x*cz+front.y*sz,-front.x*sz+front.y*cz);',
    '  front/=max(abs(vec2(cy,cx)),vec2(.38));',
    '  float frontRadius=length(front);',
    '  float foreground=smoothstep(.41,.50,frontRadius)*(1.0-smoothstep(.96,1.07,frontRadius));',
    '  vAlpha*=1.0-recessWeight*foreground*uHome;',
    '  vAlpha*=mix(1.0,mix(.20,1.0,uHome),recessWeight);',
    // Compression increases density; finer points preserve the spiral's detail.
    '  vAlpha*=mix(1.0,.22,recessWeight*uSurface.z*uHome);',
    '  float surfaceSize=mix(2.6+aSeed*.8+crest*.5,1.1+aSeed*.45,uSurface.z*uHome);',
    '  gl_PointSize=mix(gl_PointSize,surfaceSize*uPixelRatio,recessWeight);',
    /* Flux Protocol palette: steel-cyan body, dim cyan/violet/amber surface tints. */
    '  vColor=mix(vec3(.24,.33,.35),vec3(.90,.93,.95),light);',
    '  vec3 tint=vec3(.35,.58,.62)*uSurface.x+vec3(.56,.50,.74)*uSurface.z+vec3(.77,.64,.41)*uSurface.w;',
    '  tint=mix(vec3(.40,.40,.48),tint,uHome);',
    '  vColor=mix(vColor,tint*(.8+sheetLight*.2),recessWeight);',
    '  vColor=mix(vColor,mix(vec3(.12,.19,.17),tint*.42,recessWeight),uLightTheme);',
    '  vAlpha*=mix(1.0,1.65,uLightTheme);',
    '  vec3 iceColor=mix(vec3(.10,.32,.44),vec3(.76,.93,1.0),aIceberg.w);',
    '  iceColor=mix(iceColor,iceColor*.40,uLightTheme);',
    '  vColor=mix(vColor,iceColor,uReferenceA.w);',
    '  float iceAlpha=mix(.12,.85,aIceberg.w)*(1.0-step(.01,uTrail));',
    '  vAlpha=mix(vAlpha,iceAlpha,uReferenceA.w);',
    '  gl_PointSize=mix(gl_PointSize,(1.5+aSeed*.65)*uPixelRatio,uReferenceA.w);',
    '}'
  ].join('\n');

  var fragmentSource = [
    'precision mediump float;',
    'varying mediump float vAlpha;',
    'varying mediump vec3 vColor;',
    'varying mediump float vSeed;',
    'void main(){',
    '  vec2 q=gl_PointCoord-.5;',
    '  float d=length(q)*2.0;',
    '  if(d>1.0) discard;',
    '  float disc=(1.0-smoothstep(.18,1.0,d));',
    '  float core=(1.0-smoothstep(0.0,.38,d));',
    '  float noise=fract(sin(dot(floor(gl_PointCoord*12.0)+vSeed*97.0,vec2(12.9898,78.233)))*43758.5453);',
    '  float alpha=(disc*.66+core*.34)*vAlpha*mix(.45,1.35,noise);',
    '  gl_FragColor=vec4(vColor,alpha);',
    '}'
  ].join('\n');

  return Object.freeze({ vertex: vertexSource, fragment: fragmentSource });
})();
