// Bundle the existing ARK engines for the site's file:// compatible entry point.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const shared = process.argv[2] || '/Volumes/PortableSSD/shared';
const sources = ['flux-state/src/store.js', 'ark-a11y/src/element-style.js', 'ark-ui/dist/ark-ui.animate.js'];
const chunks = sources.map(file => {
  const source = fs.readFileSync(path.join(shared, file), 'utf8');
  const hash = crypto.createHash('sha256').update(source).digest('hex');
  return '// Source: ' + file + '\n// SHA256: ' + hash + '\n' + source.replace(/^import .*;\n/gm, '').replace(/^export /gm, '');
});
fs.writeFileSync(path.join(__dirname, '../js/ark/vendor/engines.js'), '/* Generated by scripts/sync-ark.cjs. Do not edit. */\nvar ArkEngines = (function () {\n\'use strict\';\n' + chunks.join('\n') + '\nreturn { FluxMemoryStore, FluxAnimate, setArkElementStyle, getArkElementStyle, setArkElementStyles, setArkElementHidden };\n})();\n');
