/* Generated by scripts/sync-reference-docs.cjs from public canonical links. */
ArkUI.referenceDocs = Object.freeze([
  "docs/evidence/bench-001-verification.md",
  "docs/evidence/bench-003-rust-fleet-ceiling.md",
  "docs/evidence/cap-004-verification.md",
  "docs/evidence/fxn-speed-audit-v0.md",
  "docs/evidence/public-claim-inventory.md",
  "docs/evidence/registry.md",
  "docs/mainnet-readiness.md",
  "docs/operators/networks.md",
  "docs/operators/prerequisites.md",
  "docs/operators/run-from-source.md",
  "docs/operators/troubleshooting.md",
  "docs/operators/verification.md",
  "docs/protocol/agreements.md",
  "docs/protocol/authority.md",
  "docs/protocol/benchmarks.md",
  "docs/protocol/governance.md",
  "docs/protocol/resolvers.md",
  "docs/status.md"
]);
