/* Generated by scripts/sync-reference-docs.cjs from public canonical links. */
ArkUI.referenceDocs = Object.freeze([
  "docs/evidence/cap-004-verification.md",
  "docs/evidence/public-claim-inventory.md",
  "docs/evidence/registry.md",
  "docs/operators/networks.md",
  "docs/operators/prerequisites.md",
  "docs/operators/run-from-source.md",
  "docs/operators/troubleshooting.md",
  "docs/operators/verification.md",
  "docs/protocol/agreements.md",
  "docs/protocol/authority.md",
  "docs/protocol/benchmarks.md",
  "docs/protocol/governance.md",
  "docs/protocol/resolvers.md",
  "docs/status.md"
]);
